### ISSUE TITLE
[FEATURE] Add more confiruation options for the ngrok tunnel

### ISSUE THREAD

**Issue by kriss-s** [zufardhiyaulhaq/ngrok-operator#10]
Looking to use this ngrok-operator, however there are some things currently missing.

I would like to be able to set more of the configuration options on the tunnels, like limiting it to TLS only (set mode tls instead of tcp/http), set the subdomain instead of full host-name and rewriting the host header.

Referenced https://ngrok.com/docs#tunnel-definitions for available configuration items.

**Comment by zufardhiyaulhaq** [comment]
I will make 
- TLS mode
- rewriting host header to upstream

into v1.2.0

**Comment by zufardhiyaulhaq** [comment]
@kriss-s what is the diff between subdomain & hostname? In hostname, we can add our own domain

**Comment by kriss-s** [comment]
Yes, subdomain let's you specify a subdomain of `ngrok.io`. Register `mydomain` in `eu` region and it will be made available as `mydomain.eu.ngrok.io`. And in the config just set `subdomain: mydomain`, no need to provide full hostname.

`hostname` on the other hand let's you set it to whatever you want (as you have in your example), but you have to provide the DNS entry yourself.
