### ISSUE TITLE
[FEATURE] Add arm64 binaries

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [zufardhiyaulhaq/ngrok-operator#19]
I am developing a cluster based on Raspberry Pis and this project would come extremely handy in that. Just that, it seems like it doesn't have arm64 support. I am open to helping in any way necessary.

**Comment by zufardhiyaulhaq** [comment]
Hi, thank you for the contribution!
that will be awesome!

I am assign this to you

**Comment by zufardhiyaulhaq** [comment]
firstly sorry I cannot help that much on this since I have never played with ARM architecture. I think I will consider to setup k8s on raspberry-based, but I think it will take some time.
