### ISSUE TITLE
[FEATURE] Use a single agent for multiple tunnels

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [zufardhiyaulhaq/ngrok-operator#23]
**Is your feature request related to a problem? Please describe.**
Right now, Ngrok pro only allows 2 agent processes to be run simultaneously. This makes it impossible to create more than 2 ngrok resources in the cluster as each resource starts a new agent pod.

**Describe the solution you'd like**
Instead of creating individual agent pods for each tunnel, one can run a single pod and update the tunnel configmap with the ngrok resources.

**Describe alternatives you've considered**
Another way could be to allow a single resource to create multiple tunnels but that doesn't seem to be an elegant idea.

**Additional context**
The architecture might need to be redesigned a bit so that the ngrok pod can access multiple namespaces probably via some rolebindings or a cluster role binding (I prefer CRB).

**Comment by zufardhiyaulhaq** [comment]
Hi @SayakMukhopadhyay can you give me the documentation on the update? this will be a major change I think. need to carefully design the changes.

**Comment by SayakMukhopadhyay** [comment]
Yeah, it has to be a new major version for sure. I don't have a detailed documentation as of yet but I can surely help out in designing it. Let me know if you want to know anything specific that I can respond to before that.
