### ISSUE TITLE
[FEATURE/QUESTION] ngrok health status

### ISSUE THREAD

**Issue by davidkarlsen** [zufardhiyaulhaq/ngrok-operator#4]
This is more of a question really, but have you found a way to properly introspect ngrok health? There is a UI at http://localhost:4040/status which shows status "online" but it's behind a lot of js-bs. I haven't found a clean API to introspect for tunnel-health.

**Comment by zufardhiyaulhaq** [comment]
I think ngrok health is not only for localhost, it's actually exposing to an IP. 
https://github.com/zufardhiyaulhaq/ngrok-operator/blob/b14b7fb1f437f9298c5de845aebe2df78fa494bc/controllers/ngrok_controller.go#L109-L115

currently, the ngrok-operator is not creating any Kubernetes services, with Kubernetes services, you can check the ngrok health with `kubectl port-forward`. will add this as a feature in the next releases.

**Comment by davidkarlsen** [comment]
yeah, I was more thinking of can a [probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) be added the the ngrok container, in order to restart it if the tunnel starts to malfunc.

**Comment by zufardhiyaulhaq** [comment]
@davidkarlsen we can handle this with 2 things
- reconciler check the domain every x minutes, actually, if you curl an expired session, it will return a 402 Error. the reconciler can check and recreate the pod.
- implement a headless browser that can handle javascript and using parser to check if the session is expired.

**Comment by davidkarlsen** [comment]
The first option seems to easiest.

**Comment by zufardhiyaulhaq** [comment]
yes, I am working on the feature right now

**Comment by zufardhiyaulhaq** [comment]
Hi @davidkarlsen I already implement this feature, it can automatically generate a new ngrok domain when expired.

**Comment by davidkarlsen** [comment]
@zufardhiyaulhaq that's awesome! :-) I'll have my colleague @otterian look into it
