### ISSUE TITLE
[FEATURE] refer secret for the token

### ISSUE THREAD

**Issue by davidkarlsen** [zufardhiyaulhaq/ngrok-operator#7]
**Is your feature request related to a problem? Please describe.**
feature.
It would be nice if https://github.com/zufardhiyaulhaq/ngrok-operator/blob/master/api/v1alpha1/ngrok_types.go#L39 could reference a tokenRef instead, so that the token could be in a secret, like in https://github.com/evryfs/github-actions-runner-operator/blob/master/api/v1alpha1/githubactionrunner_types.go#L47

**Describe the solution you'd like**
Refer token via secret to increase security.

**Describe alternatives you've considered**
use sops on the CR, but this makes it a bit more cumbersome.

**Additional context**

**Comment by zufardhiyaulhaq** [comment]
I am also thinking of this, it's more secure using secret. we need to expand the CRD for this one too works. Will add this to next milestone

**Comment by davidkarlsen** [comment]
help wanted? You want a PR?

**Comment by davidkarlsen** [comment]
I could do a PR, but don't know how to read secrets from within the template in the util package.

**Comment by zufardhiyaulhaq** [comment]
Hi, I cannot full-time works on this, please expect a delay, contribution is open. we need to define the template for the secrets, like the secret data keys that contain the data, it's just base64, we can just read the secret, decode it, and populate the AuthToken in ngrok spec.
