### ISSUE TITLE
[FEATURE] ngrok image configurable

### ISSUE THREAD

**Issue by davidkarlsen** [zufardhiyaulhaq/ngrok-operator#8]
**Is your feature request related to a problem? Please describe.**
Allow user to define an image to use in the CR. Default to existing image.

**Describe the solution you'd like**
Let users provide their own ngrok image.

**Describe alternatives you've considered**
N/A

**Additional context**
Users might have to add stuff to image, or feel more confident with own image.

**Comment by zufardhiyaulhaq** [comment]
I am not sure if this is necessary, but let me add it to the backlog

**Comment by zufardhiyaulhaq** [comment]
I think this makes sense due to the docker rate-limiting policy, will add this to v1.2
